# Project: mwfractal
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = src/main.o src/ProgramOptions.o src/utils.o src/colourizers/Colourizer.o src/colourizers/MW_Darts_Violet_to_Red.o src/colourizers/NEM_Violet_to_Red.o src/colourizers/NEM_Violet_to_Red_Lightness.o src/colourizers/NEM_White_to_Black.o src/generators/Generator.o src/generators/Julia.o src/generators/Mandelbrot.o src/image_wrapper/imageWrapper.o src/image_wrapper/LTexture.o
LINKOBJ  = src/main.o src/ProgramOptions.o src/utils.o src/colourizers/Colourizer.o src/colourizers/MW_Darts_Violet_to_Red.o src/colourizers/NEM_Violet_to_Red.o src/colourizers/NEM_Violet_to_Red_Lightness.o src/colourizers/NEM_White_to_Black.o src/generators/Generator.o src/generators/Julia.o src/generators/Mandelbrot.o src/image_wrapper/imageWrapper.o src/image_wrapper/LTexture.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"C:/ProgramData/SDL2-2.0.3/x86_64-w64-mingw32/lib" -L"C:/ProgramData/SDL2_image-2.0.0/x86_64-w64-mingw32/lib" -L"C:/ProgramData/SDL2_ttf-2.0.12/x86_64-w64-mingw32/lib" -L"C:/ProgramData/SDL2_mixer-2.0.0/x86_64-w64-mingw32/lib" -L"C:/ProgramData/boost_1_57_0" -L"C:/ProgramData/freeglut/lib" -L"C:/ProgramData/glew-1.12.0/lib/Release/x64" -L"C:/tenthLevelGames/Multi-useClasses" -L"C:/ProgramData/gmp-6.0.0" -L"C:/ProgramData/boost_1_57_0/libs" -L"C:/ProgramData/boost_1_57_0/stage/lib" -L"C:/ProgramData/jpeg-6b" -static-libgcc -lmingw32 -lboost_program_options-mgw48-mt-1_57 -lboost_program_options-mgw48-mt-d-1_57 -lSDL2main -lSDL2 -lSDL2_image -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/tenthLevelGames/mwfractal/src/image_wrapper"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++" -I"C:/ProgramData/SDL2_image-2.0.0/x86_64-w64-mingw32/include/SDL2" -I"C:/ProgramData/SDL2-2.0.3/x86_64-w64-mingw32/include/SDL2" -I"C:/ProgramData/SDL2_ttf-2.0.12/x86_64-w64-mingw32/include/SDL2" -I"C:/ProgramData/SDL2_mixer-2.0.0/x86_64-w64-mingw32/include/SDL2" -I"C:/ProgramData/boost_1_57_0" -I"C:/ProgramData/freeglut/include/GL" -I"C:/ProgramData/glew-1.12.0/include" -I"C:/tenthLevelGames/Multi-useClasses" -I"C:/ProgramData/gmp-6.0.0" -I"C:/ProgramData/boost_1_57_0/stage/lib" -I"C:/ProgramData/jpeg-6b" -I"C:/tenthLevelGames/mwfractal/src/image_wrapper"
BIN      = mwfractal.exe
CXXFLAGS = $(CXXINCS) -Werror -g3
CFLAGS   = $(INCS) -Werror -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o src/main.o $(CXXFLAGS)

src/ProgramOptions.o: src/ProgramOptions.cpp
	$(CPP) -c src/ProgramOptions.cpp -o src/ProgramOptions.o $(CXXFLAGS)

src/utils.o: src/utils.cpp
	$(CPP) -c src/utils.cpp -o src/utils.o $(CXXFLAGS)

src/colourizers/Colourizer.o: src/colourizers/Colourizer.cpp
	$(CPP) -c src/colourizers/Colourizer.cpp -o src/colourizers/Colourizer.o $(CXXFLAGS)

src/colourizers/MW_Darts_Violet_to_Red.o: src/colourizers/MW_Darts_Violet_to_Red.cpp
	$(CPP) -c src/colourizers/MW_Darts_Violet_to_Red.cpp -o src/colourizers/MW_Darts_Violet_to_Red.o $(CXXFLAGS)

src/colourizers/NEM_Violet_to_Red.o: src/colourizers/NEM_Violet_to_Red.cpp
	$(CPP) -c src/colourizers/NEM_Violet_to_Red.cpp -o src/colourizers/NEM_Violet_to_Red.o $(CXXFLAGS)

src/colourizers/NEM_Violet_to_Red_Lightness.o: src/colourizers/NEM_Violet_to_Red_Lightness.cpp
	$(CPP) -c src/colourizers/NEM_Violet_to_Red_Lightness.cpp -o src/colourizers/NEM_Violet_to_Red_Lightness.o $(CXXFLAGS)

src/colourizers/NEM_White_to_Black.o: src/colourizers/NEM_White_to_Black.cpp
	$(CPP) -c src/colourizers/NEM_White_to_Black.cpp -o src/colourizers/NEM_White_to_Black.o $(CXXFLAGS)

src/generators/Generator.o: src/generators/Generator.cpp
	$(CPP) -c src/generators/Generator.cpp -o src/generators/Generator.o $(CXXFLAGS)

src/generators/Julia.o: src/generators/Julia.cpp
	$(CPP) -c src/generators/Julia.cpp -o src/generators/Julia.o $(CXXFLAGS)

src/generators/Mandelbrot.o: src/generators/Mandelbrot.cpp
	$(CPP) -c src/generators/Mandelbrot.cpp -o src/generators/Mandelbrot.o $(CXXFLAGS)

src/image_wrapper/imageWrapper.o: src/image_wrapper/imageWrapper.cpp
	$(CPP) -c src/image_wrapper/imageWrapper.cpp -o src/image_wrapper/imageWrapper.o $(CXXFLAGS)

src/image_wrapper/LTexture.o: src/image_wrapper/LTexture.cpp
	$(CPP) -c src/image_wrapper/LTexture.cpp -o src/image_wrapper/LTexture.o $(CXXFLAGS)
